name: LamMailBox
version: '${project.version}'
main: com.yusaki.lammailbox.LamMailBox
api-version: '1.20'
folia-supported: true
description: A secure mailbox system for sending items, messages and commands between players
commands:
  smb:
    description: Main command for LamMailBox
    usage: /<command> [player|view <mailId>]
    aliases: [mailbox, mail]
  smp:
    description: Open another player's mailbox
    usage: /<command> <player>
    permission: lammailbox.open.others
  smbreload:
    description: Reload the plugin configuration
    usage: /<command>
    permission: lammailbox.reload

permissions:
  lammailbox.admin:
    description: Gives access to all admin features
    default: op
  lammailbox.open:
    description: Allows opening own mailbox
    default: true
  lammailbox.open.others:
    description: Allows opening other players' mailboxes
    default: op
  lammailbox.compose:
    description: Allows composing new mail
    default: true
  lammailbox.items:
    description: Allows adding items to mail
    default: true
  lammailbox.reload:
    description: Allows reloading the plugin configuration
    default: op
