name: SecureMailBox
version: '${project.version}'
main: me.zivush.securemailbox.SecureMailBox
api-version: '1.20'
folia-supported: true
description: A secure mailbox system for sending items, messages and commands between players
commands:
  smb:
    description: Main command for SecureMailBox
    usage: /<command> [player|view <mailId>]
    aliases: [mailbox, mail]
  smp:
    description: Open another player's mailbox
    usage: /<command> <player>
    permission: securemailbox.open.others
  smbreload:
    description: Reload the plugin configuration
    usage: /<command>
    permission: securemailbox.reload

permissions:
  securemailbox.admin:
    description: Gives access to all admin features
    default: op
  securemailbox.open:
    description: Allows opening own mailbox
    default: true
  securemailbox.open.others:
    description: Allows opening other players' mailboxes
    default: op
  securemailbox.compose:
    description: Allows composing new mail
    default: true
  securemailbox.items:
    description: Allows adding items to mail
    default: true
  securemailbox.reload:
    description: Allows reloading the plugin configuration
    default: op